import { Client, Storage, ID, Permission, Role } from "node-appwrite";
import { InputFile } from "node-appwrite/file";

const client = new Client();

// Configuration check
const isConfigured = Boolean(
  process.env.APPWRITE_ENDPOINT &&
  process.env.APPWRITE_PROJECT_ID &&
  process.env.APPWRITE_API_KEY &&
  process.env.APPWRITE_BUCKET_ID,
);

if (isConfigured) {
  client
    .setEndpoint(process.env.APPWRITE_ENDPOINT)
    .setProject(process.env.APPWRITE_PROJECT_ID)
    .setKey(process.env.APPWRITE_API_KEY);
}

const storage = new Storage(client);
const BUCKET_ID = process.env.APPWRITE_BUCKET_ID;
export { BUCKET_ID };
export const REVIEW_BUCKET_ID = process.env.APPWRITE_REVIEW_BUCKET_ID;
// Separate bucket for the front/back composite PNGs generated by the
// customizer (see customProductController.js). Kept apart from the regular
// product bucket so customer-generated designs can have their own
// lifecycle/retention/permissions without touching catalog product images.
export const CUSTOM_BUCKET_ID = process.env.APPWRITE_CUSTOM_BUCKET_ID;

export const isAppwriteConfigured = () => isConfigured;

// None of the calls below previously had any timeout — if Appwrite's API
// is unreachable or slow (e.g. restricted outbound network egress from the
// production host, which fits observed symptoms: every Appwrite-touching
// endpoint fails, everything that never leaves the server works fine),
// they'd hang indefinitely with no way to fail cleanly. That kind of hang
// is what eventually gets killed uncleanly by an upstream proxy/timeout —
// producing a connection reset/no-response that the browser can't
// distinguish from "blocked by CORS" (there's no response to attach CORS
// headers to at all). Wrapping every call means a genuine connectivity
// problem fails fast with a specific, loggable error instead.
const APPWRITE_TIMEOUT_MS = Number(process.env.APPWRITE_TIMEOUT_MS) || 20000;

const withTimeout = async (promise, label) => {
  let timer;
  try {
    return await Promise.race([
      promise,
      new Promise((_, reject) => {
        timer = setTimeout(
          () =>
            reject(
              new Error(
                `Appwrite ${label} timed out after ${APPWRITE_TIMEOUT_MS}ms — check the production server's outbound network access to APPWRITE_ENDPOINT (${process.env.APPWRITE_ENDPOINT}).`,
              ),
            ),
          APPWRITE_TIMEOUT_MS,
        );
      }),
    ]);
  } finally {
    clearTimeout(timer);
  }
};

// ---------- Helpers ----------
// ✅ FIXED — internal path only, no Appwrite details exposed
export const buildProductFileViewUrl = (fileId) =>
  `/api/images/product/${fileId}`;
export const buildReviewFileViewUrl = (fileId) =>
  `/api/images/review/${fileId}`;
export const buildCustomFileViewUrl = (fileId) =>
  `/api/images/custom/${fileId}`;

// Internal URL "kind" -> which bucket that kind actually lives in. Centralized
// here so every caller resolves the bucket the same way instead of each one
// separately assuming/hardcoding BUCKET_ID (that assumption is exactly what
// used to make custom-product image lookups/deletes silently target the
// wrong bucket).
const KIND_TO_BUCKET_ID = {
  product: BUCKET_ID,
  review: REVIEW_BUCKET_ID,
  custom: CUSTOM_BUCKET_ID,
};

export const extractFileIdFromUrl = (url) => {
  if (typeof url !== "string") return null;
  // New internal format: /api/images/product|review|custom/<fileId>
  const internalMatch = url.match(
    /\/api\/images\/(?:product|review|custom)\/([^/?]+)/,
  );
  if (internalMatch) return internalMatch[1];
  // Legacy raw Appwrite URL format, for images stored before this fix
  const legacyMatch = url.match(/\/files\/([^/]+)\/(?:view|download|preview)/);
  return legacyMatch ? legacyMatch[1] : null;
};

// A file view URL is /storage/buckets/{bucketId}/files/{fileId}/view — the
// bucket a file lives in is NOT always the product-images bucket (e.g.
// try-on result images, uploaded by the separate try-on microservice, live
// in their own bucket). Every place that fetches file bytes by URL must use
// THIS bucket id, not an assumed/hardcoded one, or the lookup 404s against
// the wrong bucket.
export const extractBucketIdFromUrl = (url) => {
  if (typeof url !== "string") return null;
  const match = url.match(/\/buckets\/([^/]+)\/files\//);
  return match ? match[1] : null;
};

// The single source of truth for "which bucket does this file URL live
// in?", covering both URL shapes in use:
//   - internal: /api/images/<kind>/<fileId>  -> kind maps to its bucket
//   - legacy:   .../buckets/<bucketId>/files/<fileId>/view -> bucket is in the URL
// Anything that needs to fetch/delete a file by URL (image proxy, product
// image delete, try-on cloth image lookup, etc.) should go through this
// instead of assuming BUCKET_ID, so it keeps working for review/custom/
// legacy images too.
export const resolveBucketIdForUrl = (url) => {
  if (typeof url !== "string") return null;
  const internalMatch = url.match(/\/api\/images\/(product|review|custom)\//);
  if (internalMatch) return KIND_TO_BUCKET_ID[internalMatch[1]] ?? null;
  return extractBucketIdFromUrl(url);
};

export const isAppwriteFileUrl = (url) => {
  if (typeof url !== "string" || !process.env.APPWRITE_ENDPOINT) return false;
  return (
    url.startsWith(process.env.APPWRITE_ENDPOINT) &&
    extractFileIdFromUrl(url) !== null
  );
};

// ---------- Product Images ----------

export const uploadFileToAppwrite = async (buffer, filename) => {
  if (!isConfigured) {
    throw new Error(
      "Appwrite is not configured: set APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_BUCKET_ID",
    );
  }

  const file = InputFile.fromBuffer(buffer, filename);
  const created = await withTimeout(
    storage.createFile({
      bucketId: BUCKET_ID,
      fileId: ID.unique(),
      file,
      permissions: [Permission.read(Role.any())],
    }),
    "createFile (product image)",
  );

  return buildProductFileViewUrl(created.$id);
};

// bucketId defaults to the product bucket for backward compatibility with
// existing call sites that only ever deleted product images; callers that
// might be deleting a review/custom/legacy file should resolve the right
// bucket first (see resolveBucketIdForUrl) and pass it explicitly.
export const deleteFileFromAppwrite = async (fileId, bucketId = BUCKET_ID) => {
  if (!isConfigured) return;
  await withTimeout(
    storage.deleteFile({ bucketId, fileId }),
    "deleteFile (product image)",
  );
};

export const getFileBuffer = async (bucketId, fileId) => {
  if (!isConfigured) {
    throw new Error(
      "Appwrite is not configured: set APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_BUCKET_ID",
    );
  }

  const result = await withTimeout(
    storage.getFileDownload({ bucketId, fileId }),
    "getFileDownload",
  );
  return Buffer.isBuffer(result) ? result : Buffer.from(result);
};

// File metadata (includes the real mimeType) — used by the image proxy so
// downloaded/served files get an accurate Content-Type instead of a guess
// based on the URL's (often absent) file extension.
export const getFileMeta = async (bucketId, fileId) => {
  if (!isConfigured) {
    throw new Error(
      "Appwrite is not configured: set APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_BUCKET_ID",
    );
  }
  return withTimeout(storage.getFile({ bucketId, fileId }), "getFile (meta)");
};

// ---------- Review Images (CRUD) ----------

export const uploadReviewFileToAppwrite = async (buffer, filename) => {
  if (!isConfigured || !REVIEW_BUCKET_ID) {
    throw new Error(
      "Appwrite is not configured: set APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_REVIEW_BUCKET_ID",
    );
  }

  const file = InputFile.fromBuffer(buffer, filename);
  const created = await withTimeout(
    storage.createFile({
      bucketId: REVIEW_BUCKET_ID,
      fileId: ID.unique(),
      file,
      permissions: [Permission.read(Role.any())],
    }),
    "createFile (review image)",
  );

  return buildReviewFileViewUrl(created.$id);
};

export const getReviewFileMeta = async (fileId) => {
  if (!isConfigured || !REVIEW_BUCKET_ID) {
    throw new Error("Appwrite not configured for review bucket");
  }
  return withTimeout(
    storage.getFile({ bucketId: REVIEW_BUCKET_ID, fileId }),
    "getFile (review image)",
  );
};

export const updateReviewFile = async (fileId, buffer, filename) => {
  if (!isConfigured || !REVIEW_BUCKET_ID) {
    throw new Error("Appwrite not configured for review bucket");
  }

  // Delete old file
  await withTimeout(
    storage.deleteFile({ bucketId: REVIEW_BUCKET_ID, fileId }),
    "deleteFile (review image, old)",
  );

  // Upload new file
  const file = InputFile.fromBuffer(buffer, filename);
  const created = await withTimeout(
    storage.createFile({
      bucketId: REVIEW_BUCKET_ID,
      fileId: ID.unique(),
      file,
      permissions: [Permission.read(Role.any())],
    }),
    "createFile (review image, replacement)",
  );

  return buildReviewFileViewUrl(created.$id);
};

export const deleteReviewFile = async (fileId) => {
  if (!isConfigured || !REVIEW_BUCKET_ID) return;
  await withTimeout(
    storage.deleteFile({ bucketId: REVIEW_BUCKET_ID, fileId }),
    "deleteFile (review image)",
  );
};

// ---------- Customized Product Images (generated designs) ----------

export const isCustomBucketConfigured = () => Boolean(isConfigured && CUSTOM_BUCKET_ID);

export const uploadCustomFileToAppwrite = async (buffer, filename) => {
  if (!isConfigured || !CUSTOM_BUCKET_ID) {
    throw new Error(
      "Appwrite is not configured: set APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_CUSTOM_BUCKET_ID",
    );
  }

  const file = InputFile.fromBuffer(buffer, filename);
  const created = await withTimeout(
    storage.createFile({
      bucketId: CUSTOM_BUCKET_ID,
      fileId: ID.unique(),
      file,
      permissions: [Permission.read(Role.any())],
    }),
    "createFile (custom product image)",
  );

  return buildCustomFileViewUrl(created.$id);
};

export const deleteCustomFileFromAppwrite = async (fileId) => {
  if (!isConfigured || !CUSTOM_BUCKET_ID) return;
  await withTimeout(
    storage.deleteFile({ bucketId: CUSTOM_BUCKET_ID, fileId }),
    "deleteFile (custom product image)",
  );
};
